### ISSUE TITLE
Heroku deployment - App crashes due to missing 'rails_12factor' gem

### ISSUE THREAD

**Issue by mr-rob0to** [mhartl/rails_tutorial_4th_edition_gemfiles#1]
Once the application is deployed to heroku, the application crashes and does not startup.  After researching the log files and SO, it appears Heroku requires the following gem to be installed: 

**gem 'rails_12factor', '0.0.2'**

After adding this to the Gemfile under the **group :production do** and doing a **bundle install** locally, I was able to push my changes to Heroku and deploy successfully.  This gem should be included as part of the Heroku deployment section in the tutorial.

**Comment by jpkeane** [comment]
Hi Sergeant-q,

12-factor is not required with Rails 5 as the new defaults are compatible with 12factor. Are you sure you have installed the correct version of Rails.

Also, you would need to provide more details than 'crashes' - the 12factor gem itself only changes some configuration around serving assets and logging, therefore wouldn't cause, say, a controller to return a status 500.

Suggest tagging invalid and closing.

**Comment by mr-rob0to** [comment]
@jpkeane 

Oddly enough it's working now.  It may have been a miss on my part on running the right rails version, though I'm pretty sure I was using **5.0.0**.  In any case, thanks for looking into this.  I'll close this issue it out.

**Comment by jpkeane** [comment]
Glad its working now @sergeant-q! Good luck with the rest of the tutorial!

For anyone else looking, my best guess would be that you had 2 rails versions installed at the time of new app, the Gemfile was updated via copy and past from the tutorial, but Gemfile.lock wasn't updated before deploying to Heroku. Running bundle install when adding 12factor updated Gemfile.lock, and the next deployment worked on the correct Rails version!
